localStorage
localStorage.setItem('MrngJavaScipt',5)
undefined
localStorage.getItem('MrngJavaScipt')
"5"
localStorage.removeItem('MrngJavaScript')
undefined
localStorage.getItem('MrngJavaScipt')
"5"
localStorage.removeItem('MrngJavaScipt')
undefined
localStorage.getItem('MrngJavaScipt')
null
localStorage.removeItem('MrngJavaScript')
undefined
localStorage.setItem('MrngJavaScipt',5)
undefined
localStorage.setItem('MrngJavaScipt',['a','b'])